import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppContainer from "./components/AppContainer/AppContainer";
import Header from "./components/Header/Header";
// import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Embedding Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContainer>
          <Header />
          {children}
          {/* <Footer /> */}
        </AppContainer>
      </body>
    </html>
  );
}
